language:
  - python
python:
  - "2.7"
install:
  - git fetch --unshallow
  - cd backend
  - pip install --upgrade setuptools pip
  - pip install tox
script:
  - tox -- --tb=native
notifications:
  irc:
    - "irc.freenode.org#pyfidelity"
  email:
    - mail@pyfidelity.com
sudo: false
