language:
  - python
python:
  - "2.7"
install:
  - cd backend
  - pip install --upgrade setuptools pip
  - pip install setuptools-git
  - pip install tox
script:
  - git describe --tags --long --dirty
  - tox -- --tb=native
notifications:
  irc:
    - "irc.freenode.org#pyfidelity"
  email:
    - mail@pyfidelity.com
sudo: false
addons:
  apt:
    packages:
    - git
